### PR TITLE
Add external update URL

### PR DESCRIPTION
**Pull request by clouserw**

### CODE REVIEW

**Comment by rchrd2** [comment]
This looks good. A few questions though:

- Does this endpoint exist already? 
- Will it cause issues if this endpoint is unreachable? 
- What happens if the plugin installed locally is newer than the remote version?

Thanks. -R

**Comment by clouserw** [comment]
* Yes, the endpoint exists
* No.  Firefox will ignore it if it can't reach it
* it won't update (where "newer" is defined by the version number)

**Comment by rchrd2** [comment]
Great thanks.

**Comment by pdehaan** [comment]
Any chance we can push a new build to the CDN (or wherever it's hosted) and test the auto-updating before we launch?

I currently have v1.5.0 installed from testpilot.dev.mozaws.net and it says no newer versions are available.

**Comment by rchrd2** [comment]
I don't have the access to push to the CDN. I just pushed the v1.5.1 build to github.

**Comment by clouserw** [comment]
Yeah, I'm going to put it on the CDN, but 1.5.0 won't auto-update.  1.5.1 was the first version to get the update_url, so we'd need to make a 1.5.2 to test it.  I do think we should.

**Comment by rchrd2** [comment]
Okay. Would you like me to bump the version so you can test it?

**Comment by clouserw** [comment]
That would be great.  Then I'll add both versions to the CDN at the same time.

**Comment by rchrd2** [comment]
v1.5.2 has been pushed.

**Comment by clouserw** [comment]
Well... The good news is, they are on the CDN and I think will work correctly.  The bad news is, cloudfront is caching the shit out of the json file so we can't actually get the update prompt.  I forget how long cloudfront's cache is by default, but I'll ping ops in the morning to figure out how we'll handle this in the future.  CURLing the file gets the JSON I want, so we're part way there at least.

https://testpilot.cdn.mozilla.net/nomore404s/nomore404s.json
https://testpilot.cdn.mozilla.net/nomore404s/wayback_machine-1.5.1-fx.xpi
https://testpilot.cdn.mozilla.net/nomore404s/wayback_machine-1.5.2-fx.xpi

@pdehaan if you have a way to check if they'll update, please do :)

**Comment by pdehaan** [comment]
cURLing works, but it looks like http://testpilot.dev.mozaws.net/api/experiments?format=json points to a hard-coded 1.5.0 XPI, which may explain why deleting and reinstalling the experiment always gives me the non-auto-updating the v1.5.0 add-on.

```js
xpi_url: "https://testpilot.cdn.mozilla.net/nomore404s/wayback_machine-1.5.0-fx.xpi",
```

Also, it may be easier if we rename the XPI to something boring and predictable, like "latest.xpi", so we don't have to worry about updating the admin site every time we push a new add-on to S3.

**Comment by clouserw** [comment]
Wooo, I installed 1.5.1 and updated to 1.5.2.

S3 doesn't know what symlinks are, so we can't have a latest.xpi unless we manually maintain it (which we could do).  Also, I set the .json file to expire every 10 minutes from the cdn.

**Comment by pdehaan** [comment]
How did you install v1.5.1? testpilot.dev.mozaws.net is still serving me v1.5.0.

**Comment by rchrd2** [comment]
@clouserw Not sure what the best choice is here. The current filename is the default filename that comes out of the "sign" command. It is nice that it has the version in the filename. 

Since you're manually copying it to the CDN, couldn't you rename it to "latest.xpi" in that step?

**Comment by wresuolc** [comment]
@pdehaan I downloaded the file from the link above and installed it locally.  Sounds like our staging server is all set up correctly though if you want to install from the website.

@rchrd2 Yeah, don't worry about it.  :)

**Comment by pdehaan** [comment]
FWIW, I tried running **addons-linter** against a freshly built `$ npm run build_unsigned` ZIP and it returns an error:

>  `applications.gecko.update_url` is not allowed for Mozilla-hosted add-ons.

Not sure how valid that error is, or if the https://testpilot.cdn.mozilla.net/nomore404s/nomore404s.json `update_url` is truly a "Mozilla-hosted add-on".

---

```sh
# Step 1:
$ npm run build_unsigned

> FirefoxNoMore404s@1.5.3 build_unsigned /Users/pdehaan/dev/github/FirefoxNoMore404s
> mkdir -p build_unsigned && web-ext build --source-dir=src --artifacts-dir=build_unsigned

Building web extension from /Users/pdehaan/dev/github/FirefoxNoMore404s/src
Your web extension is ready: build_unsigned/no_more_404s-1.5.3.zip

# Step 2:
$ npm i addons-linter

...

# Step 3:
$ ./node_modules/.bin/addons-linter build_unsigned/no_more_404s-1.5.3.zip -o text
Validation Summary:

errors          1
notices         0
warnings        0

ERRORS:

Code                  Message               Description                                      File            Line   Column
MANIFEST_UPDATE_URL   "update_url" is not   "applications.gecko.update_url" is not allowed   manifest.json
                      allowed.              for Mozilla-hosted add-ons.

# Step 4:
$ echo $? # 1
```

**Comment by wresuolc** [comment]
It means it can't be hosted on AMO.  It's fine for what we're doing.

**Comment by pdehaan** [comment]
Thanks @wresuolc.

Apparently we can pass a `--self-hosted` flag on the CLI which hides this error:

```sh
$ addons-linter build_unsigned/no_more_404s-1.5.3.zip --self-hosted -o text
Validation Summary:

errors          0
notices         0
warnings        0
```

Sorry for the noise.

**Pull request merged**
